### ISSUE TITLE
error deferencing a child-of-child object during deserialization 

### ISSUE THREAD

**Issue by cristianolongo** [kbss-cvut/jb4jsonld-jackson#2]
Le _parent_ an individual and _a_, _b_ two individuals linked to _parent_ via the properties _hasChildA_ and _hasChildA_ respectively. Now let _f_ be an individual linked both to _a_ and _b_ via the property _hasFriend_.

_parent_ _hasChildA_ _a_
_parent_ _hasChildB_ _b_
_c_ _hasFriend_ _f_
_c_ _hasFriend_ _f_

by serializing the _parent_ with the jsonld object mapper and then deserializing it, the following exception is thrown

cz.cvut.kbss.jsonld.exception.JsonLdDeserializationException: Node with IRI http://example.org/f cannot be referenced, because it has not been encountered yet.

**Comment by cristianolongo** [comment]
during deserialization, _expansion_ invert the order of _a_ and _b_ , see row 60 of JacksonJsonLdDeserializer. 

Before expansion, the _input_ variable has the following value

>{
>  @id=_:2111787781,
>  @type=[http://example.org/ParentWithTwoChildren], 
>  http://example.org/hasChildB={
>    @id=http://example.org/b, 
>    @type=[http://example.org/Child], 
>    http://example.org/hasFriend={
>      @id=http://example.org/f, 
>      @type=[http://example.org/Child]
>    }
>  }, 
>  http://example.org/hasChildA={
>    @id=http://example.org/a, 
>    @type=[http://example.org/Child], 
>    http://example.org/hasFriend={
>      @id=http://example.org/f
>    }
>  }
>}

Note that the property _hasChildB_ is placed before _hasChildA_ and `http://example.org/f`
is reported in _hasChildB_ whereas in _hasChildA_ is just referenced, as expected.

Now let us see the value of the _expanded_variable

>[{
>    @id=_:2111787781, 
>    @type=[http://example.org/ParentWithTwoChildren], 
>    http://example.org/hasChildA=[{
>      @id=http://example.org/a, 
>      @type=[http://example.org/Child], 
>      http://example.org/hasFriend=[{@id=http://example.org/f}]
>    }], 
>    http://example.org/hasChildB=[{
>      @id=http://example.org/b, 
>      @type=[http://example.org/Child], 
>      http://example.org/hasFriend=[{
>        @id=http://example.org/f, 
>        @type=[http://example.org/Child]
>      }]
>    }]
>}]

here _hasChildA_ is placed before _hasChildB_, but `http://example.org/f` is still referenced in _hasChildA_ and fully reported in _hasChildB_

**Comment by ledsoft** [comment]
Hi, good catch. If they are really two different properties (`hasChildA` and `hasChildB`), you should be able to use the `@JsonLdAttributeOrder` annotation to force processing of the object attributes in a specific order. This should work for both serialization and deserialization.
Note that the annotation value should be the Java field names, **not** the property IRIs.

**Comment by cristianolongo** [comment]
yes attribute ordering fixes the problem, however I use classes autogenerated with jopa maven plugin so that it would be inappropriate to update these

**Comment by ledsoft** [comment]
Ok, I see. This will be a bit harder. I guess what we'd have to do would be some sort of deferred reference resolution.
As a workaround, I'd try declaring a DTO which would be a subclass of the entity, with no additional attributes, just adding the ordering annotation. It is not ideal, but should work.

**Comment by ledsoft** [comment]
Tracking the issue under [#17](https://github.com/kbss-cvut/jb4jsonld/issues/17) in the core JB4JSON-LD repo.

**Comment by ledsoft** [comment]
Please, try using the latest version (0.7.0) which implements deferred reference resolution. That should resolve the problem.

**Comment by cristianolongo** [comment]
yeah I'm using it and I found no problems, thanks
